// COUNTER ACTIONS
export const INCREMENTCOUNTER = 'INCREMENTCOUNTER';
export const DECREMENTCOUNTER = 'DECREMENTCOUNTER';
export const CLEARCOUNTER = 'CLEARCOUNTER';

// TODO ACTIONS
export const ADDTODO = 'ADDTODO';
export const DELETETODO = 'DELETETODO';

// GET POST ACTIONS
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

// CREATE POST ACTIONS
export const CREATE_POSTS = 'CREATE_POSTS';
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS';
export const CREATE_POSTS_FAILURE = 'CREATE_POSTS_FAILURE';
