export const INCREMENTCOUNTER = 'INCREMENTCOUNTER';
export const DECREMENTCOUNTER = 'DECREMENTCOUNTER';
export const CLEARCOUNTER = 'CLEARCOUNTER';
export const ADDTODO = 'ADDTODO';
export const DELETETODO = 'DELETETODO';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';
